name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: npm i npm -g
      - run: npm version
      - run: npm i
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run e2e:ci
